// ╔══════════════════════════════════════════════════════════╗
// ║  AnswerResponse.cs — What the API sends back             ║
// ║                                                          ║
// ║  Analogy: You asked the bank employee a question.        ║
// ║  They looked it up in their procedure manual, found the  ║
// ║  answer, and wrote it on a paper with:                   ║
// ║  - The answer itself                                     ║
// ║  - Which manual they found it in (the source)            ║
// ╚══════════════════════════════════════════════════════════╝

namespace StbCopilot.Api.Models
{
    /// <summary>
    /// This class represents the ANSWER sent back to the frontend.
    /// After the RAG pipeline processes the question, we pack
    /// the result into this object and send it as JSON.
    /// 
    /// Example JSON sent to frontend:
    /// {
    ///     "answer": "Pour ouvrir un compte, vous devez...",
    ///     "sourceDocument": "procedure_ouverture_compte.pdf",
    ///     "confidence": 0.85
    /// }
    /// </summary>
    public class AnswerResponse
    {
        // The actual answer generated by the AI (Groq LLM).
        public string Answer { get; set; } = "";

        // The name of the PDF document where the answer was found.
        // This helps the agent verify the source.
        public string SourceDocument { get; set; } = "";

        // A number between 0 and 1 showing how confident we are.
        // Higher = the question matched a document chunk well.
        public double Confidence { get; set; }
    }
}
